# Generated by Django 5.2.12 on 2026-03-22 20:36

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('new', 'Новый'), ('processing', 'В обработке'), ('approved', 'Подтвержден'), ('exported', 'Выгружен в ERP'), ('invoiced', 'Выставлен счет'), ('shipped', 'Отгружен'), ('completed', 'Завершен'), ('cancelled', 'Отменен')], default='new', max_length=16, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='order',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='Сумма'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='Итого'),
        ),
        migrations.CreateModel(
            name='OrderStatusEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_status', models.CharField(blank=True, max_length=16, verbose_name='Предыдущий статус')),
                ('new_status', models.CharField(max_length=16, verbose_name='Новый статус')),
                ('source', models.CharField(choices=[('site', 'Сайт'), ('erp', 'ERP'), ('system', 'Система')], default='system', max_length=16, verbose_name='Источник')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('external_number', models.CharField(blank=True, max_length=64, verbose_name='Номер ERP')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_events', to='orders.order', verbose_name='Заказ')),
            ],
            options={
                'verbose_name': 'История статуса заказа',
                'verbose_name_plural': 'История статусов заказов',
                'ordering': ['-created_at'],
            },
        ),
    ]
