# Generated by Django 5.2.12 on 2026-03-23 04:37

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0003_integrationprofile_archive_path_and_more'),
        ('orders', '0002_alter_order_status_alter_order_subtotal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='can_repeat',
            field=models.BooleanField(default=True, verbose_name='Можно повторить'),
        ),
        migrations.AddField(
            model_name='order',
            name='customer_comment',
            field=models.TextField(blank=True, verbose_name='Комментарий клиента'),
        ),
        migrations.AddField(
            model_name='order',
            name='erp_document_number',
            field=models.CharField(blank=True, max_length=64, verbose_name='Номер документа ERP'),
        ),
        migrations.AddField(
            model_name='order',
            name='erp_export_state',
            field=models.CharField(choices=[('new', 'Новый'), ('validated', 'Проверен'), ('exported', 'Выгружен'), ('imported', 'Импортирован в ERP'), ('error', 'Ошибка')], db_index=True, default='new', max_length=16, verbose_name='Состояние выгрузки ERP'),
        ),
        migrations.AddField(
            model_name='order',
            name='erp_last_payload_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders_last_seen', to='integrations.exchangeartifact', verbose_name='Последний входящий файл ERP'),
        ),
        migrations.AddField(
            model_name='order',
            name='erp_status_code',
            field=models.CharField(blank=True, max_length=64, verbose_name='Код статуса ERP'),
        ),
        migrations.AddField(
            model_name='order',
            name='erp_status_label',
            field=models.CharField(blank=True, max_length=255, verbose_name='Статус ERP'),
        ),
        migrations.AddField(
            model_name='order',
            name='erp_sync_error',
            field=models.TextField(blank=True, verbose_name='Ошибка ERP'),
        ),
        migrations.AddField(
            model_name='order',
            name='erp_updated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Обновлено из ERP'),
        ),
        migrations.AddField(
            model_name='order',
            name='exported_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Выгружен в ERP'),
        ),
        migrations.AddField(
            model_name='order',
            name='external_uid',
            field=models.CharField(blank=True, db_index=True, max_length=128, unique=True, verbose_name='Внешний UID'),
        ),
        migrations.AddField(
            model_name='order',
            name='last_export_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='integrations.exchangebatch', verbose_name='Последний пакет выгрузки'),
        ),
        migrations.AddField(
            model_name='order',
            name='last_export_hash',
            field=models.CharField(blank=True, max_length=64, verbose_name='Хеш последней выгрузки'),
        ),
        migrations.AddField(
            model_name='order',
            name='locked_after_export',
            field=models.BooleanField(default=False, verbose_name='Заблокирован после выгрузки'),
        ),
        migrations.AddField(
            model_name='order',
            name='manager_comment',
            field=models.TextField(blank=True, verbose_name='Комментарий менеджера'),
        ),
        migrations.AddField(
            model_name='orderstatusevent',
            name='applied_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Применено'),
        ),
        migrations.AddField(
            model_name='orderstatusevent',
            name='payload_excerpt',
            field=models.TextField(blank=True, verbose_name='Фрагмент исходных данных'),
        ),
        migrations.AddField(
            model_name='orderstatusevent',
            name='raw_status_code',
            field=models.CharField(blank=True, max_length=128, verbose_name='Сырой код статуса'),
        ),
        migrations.AddField(
            model_name='orderstatusevent',
            name='raw_status_label',
            field=models.CharField(blank=True, max_length=255, verbose_name='Сырое название статуса'),
        ),
        migrations.AddField(
            model_name='orderstatusevent',
            name='source_file',
            field=models.CharField(blank=True, max_length=500, verbose_name='Файл-источник'),
        ),
        migrations.AlterField(
            model_name='orderstatusevent',
            name='new_status',
            field=models.CharField(max_length=32, verbose_name='Новый статус'),
        ),
        migrations.AlterField(
            model_name='orderstatusevent',
            name='previous_status',
            field=models.CharField(blank=True, max_length=32, verbose_name='Предыдущий статус'),
        ),
    ]
