# Generated by Django 5.2.12 on 2026-03-23 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='credit_limit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Кредитный лимит'),
        ),
        migrations.AddField(
            model_name='company',
            name='legal_address',
            field=models.CharField(blank=True, max_length=500, verbose_name='Юридический адрес'),
        ),
        migrations.AddField(
            model_name='company',
            name='manager_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email менеджера'),
        ),
        migrations.AddField(
            model_name='company',
            name='manager_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Ответственный менеджер'),
        ),
        migrations.AddField(
            model_name='company',
            name='shipping_address',
            field=models.CharField(blank=True, max_length=500, verbose_name='Адрес доставки'),
        ),
        migrations.AlterField(
            model_name='company',
            name='external_id',
            field=models.CharField(blank=True, db_index=True, max_length=128, unique=True, verbose_name='Внешний ID'),
        ),
    ]
