# Generated by Django 5.2.12 on 2026-03-22 20:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntegrationProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=64, unique=True, verbose_name='Код профиля')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('import_xml_path', models.CharField(blank=True, max_length=1024, verbose_name='Путь к import.xml')),
                ('offers_xml_path', models.CharField(blank=True, max_length=1024, verbose_name='Путь к offers.xml')),
                ('images_dir_path', models.CharField(blank=True, max_length=1024, verbose_name='Путь к import_files')),
                ('export_orders_path', models.CharField(blank=True, max_length=1024, verbose_name='Путь к выгрузке orders.xml')),
                ('status_feed_path', models.CharField(blank=True, max_length=1024, verbose_name='Путь к файлу статусов заказов')),
                ('run_every_minutes', models.PositiveIntegerField(default=15, verbose_name='Интервал запуска, минут')),
                ('export_only_new', models.BooleanField(default=True, verbose_name='Экспортировать только новые заказы')),
                ('notify_emails', models.CharField(blank=True, max_length=1024, verbose_name='Email для уведомлений')),
                ('last_run_at', models.DateTimeField(blank=True, null=True, verbose_name='Последний запуск')),
                ('last_success_at', models.DateTimeField(blank=True, null=True, verbose_name='Последний успешный запуск')),
                ('last_error', models.TextField(blank=True, verbose_name='Последняя ошибка')),
            ],
            options={
                'verbose_name': 'Профиль интеграции',
                'verbose_name_plural': 'Профили интеграции',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='exchangelog',
            name='finished_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Окончание'),
        ),
        migrations.AddField(
            model_name='exchangelog',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Начало'),
        ),
        migrations.AlterField(
            model_name='exchangelog',
            name='direction',
            field=models.CharField(choices=[('import', 'Импорт'), ('export', 'Экспорт'), ('status', 'Статусы'), ('system', 'Система')], max_length=16, verbose_name='Направление'),
        ),
        migrations.AddField(
            model_name='exchangelog',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='integrations.integrationprofile', verbose_name='Профиль'),
        ),
    ]
