# Generated by Django 5.2.12 on 2026-03-23 04:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0002_integrationprofile_exchangelog_finished_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='integrationprofile',
            name='archive_path',
            field=models.CharField(blank=True, max_length=1024, verbose_name='Каталог архива обмена'),
        ),
        migrations.AddField(
            model_name='integrationprofile',
            name='auto_export_enabled',
            field=models.BooleanField(default=True, verbose_name='Автоэкспорт заказов'),
        ),
        migrations.AddField(
            model_name='integrationprofile',
            name='auto_status_import_enabled',
            field=models.BooleanField(default=True, verbose_name='Автоимпорт статусов'),
        ),
        migrations.CreateModel(
            name='ERPStatusMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_code', models.CharField(blank=True, max_length=128, verbose_name='Код ERP')),
                ('source_label', models.CharField(blank=True, max_length=255, verbose_name='Статус ERP')),
                ('internal_status', models.CharField(max_length=32, verbose_name='Внутренний статус')),
                ('is_terminal', models.BooleanField(default=False, verbose_name='Терминальный')),
                ('notify_customer', models.BooleanField(default=True, verbose_name='Уведомлять клиента')),
            ],
            options={
                'verbose_name': 'Карта статуса ERP',
                'verbose_name_plural': 'Карты статусов ERP',
                'ordering': ['source_code', 'source_label'],
                'constraints': [models.UniqueConstraint(fields=('source_code', 'source_label'), name='uniq_erp_status_mapping_pair')],
            },
        ),
        migrations.CreateModel(
            name='ExchangeBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='Код пакета')),
                ('direction', models.CharField(choices=[('export_orders', 'Экспорт заказов'), ('import_statuses', 'Импорт статусов'), ('system', 'Система')], max_length=32, verbose_name='Направление')),
                ('status', models.CharField(choices=[('created', 'Создан'), ('ok', 'Успешно'), ('warning', 'Предупреждение'), ('error', 'Ошибка')], default='created', max_length=16, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Начат')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Завершен')),
                ('orders_count', models.PositiveIntegerField(default=0, verbose_name='Заказов')),
                ('success_count', models.PositiveIntegerField(default=0, verbose_name='Успешно')),
                ('error_count', models.PositiveIntegerField(default=0, verbose_name='Ошибок')),
                ('file_path', models.CharField(blank=True, max_length=1024, verbose_name='Путь к основному файлу')),
                ('checksum', models.CharField(blank=True, max_length=64, verbose_name='Checksum')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batches', to='integrations.integrationprofile', verbose_name='Профиль')),
            ],
            options={
                'verbose_name': 'Пакет обмена',
                'verbose_name_plural': 'Пакеты обмена',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExchangeArtifact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('orders_xml', 'orders.xml'), ('status_xml', 'status xml'), ('status_csv', 'status csv'), ('log', 'log')], max_length=32, verbose_name='Тип файла')),
                ('file_path', models.CharField(max_length=1024, verbose_name='Путь к файлу')),
                ('checksum', models.CharField(blank=True, max_length=64, verbose_name='Checksum')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artifacts', to='integrations.exchangebatch', verbose_name='Пакет')),
            ],
            options={
                'verbose_name': 'Артефакт обмена',
                'verbose_name_plural': 'Артефакты обмена',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='exchangelog',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='integrations.exchangebatch', verbose_name='Пакет'),
        ),
    ]
