# Generated by Django 5.2.12 on 2026-03-22 20:36

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='product',
            new_name='catalog_pro_code_31976d_idx',
            old_name='apps_catalo_code_9fe479_idx',
        ),
        migrations.RenameIndex(
            model_name='product',
            new_name='catalog_pro_barcode_58f8f8_idx',
            old_name='apps_catalo_barcode_d89544_idx',
        ),
        migrations.RenameIndex(
            model_name='product',
            new_name='catalog_pro_name_f603c0_idx',
            old_name='apps_catalo_name_80ea41_idx',
        ),
        migrations.AlterField(
            model_name='product',
            name='min_order_qty',
            field=models.DecimalField(decimal_places=3, default=Decimal('1'), max_digits=12, verbose_name='Мин. заказ'),
        ),
        migrations.AlterField(
            model_name='product',
            name='multiplicity',
            field=models.DecimalField(decimal_places=3, default=Decimal('1'), max_digits=12, verbose_name='Кратность'),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock_total',
            field=models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=14, verbose_name='Общий остаток'),
        ),
    ]
